### ISSUE TITLE
Disable Vanilla gen fixed, now my specified ores arent spawning

### ISSUE THREAD

**Issue by CheekyBrit** [Terrails/OreController#2]
Thanks for preventing the vanilla ore gen. However my config doesnt generate anything whatsoever. any ideas? 
# Configuration file

"general settings" {
    B:Generate=true

    #  [default: ]
    S:"Ore Generation" <
        minecraft:iron_ore -minVein:16 -maxVein:32 -minY:20 -maxY:30 -perChunk:16 -biome:4
        minecraft:gold_ore -minVein:20 -maxVein:40 -minY:5 -maxY:15 -perChunk:16 -biome:21
        minecraft:coal_ore -minVein:40 -maxVein:70 -minY:20 -maxY:30 -perChunk:16 -biome:1
        minecraft:lapis_ore -minVein:10 -maxVein:14 -minY:8 -maxY:12 -perChunk:16 -biome:6
        minecraft:diamond_ore -minVein:4 -maxVein:10 -minY:2 -maxY:4 -perChunk:16 -biome:35
        minecraft:redstone_ore -minVein:10 -maxVein:20 -minY:10 -maxY:20 -perChunk:16 -biome:2
        minecraft:emerald_ore -minVein:4 -maxVein:10 -minY:2 -maxY:10 -perChunk:16 -biome:3
     >
}

**Comment by Terrails** [comment]
I think it should be fixed now, just gotta wait for curse to approve the files.

**Comment by CheekyBrit** [comment]
So its now generating ores but the specific biome isnt working. config:

# Configuration file

"general settings" {
    B:Generate=true

    #  [default: ]
    S:"Ore Generation" <
 minecraft:coal_ore -minVein:40 -maxVein:70 -minY:10 -maxY:60 -perChunk:7
 minecraft:iron_ore -minVein:26 -maxVein:42 -minY:20 -maxY:50 -perChunk:7 -biome:1|129|4|132|27|155|29|157
 minecraft:gold_ore -minVein:16 -maxVein:22 -minY:10 -maxY:20 -perChunk:7 -biome:21|149|23|151
 minecraft:lapis_ore -minVein:6 -maxVein:12 -minY:10 -maxY:30 -perChunk:7 -biome:6|134
 minecraft:diamond_ore -minVein:8 -maxVein:12 -minY:10 -maxY:12 -perChunk:7 -biome:14|15
 minecraft:redstone_ore -minVein:12 -maxVein:18 -minY:10 -maxY:26 -perChunk:7 -biome:2|130|35|163|37|165|38|166|36|39
 minecraft:emerald_ore -minVein:4 -maxVein:8 -minY:10 -maxY:20 -perChunk:7 -biome:3|131|34|162|5|133|32|160
 minecraft:quartz_ore -minVein:16 -maxVein:40 -minY:0 -maxY:100 -perChunk:7 -biome:8 -dimension:-1
 actuallyadditions:block_misc|3 -minVein:6 -maxVein:12 -minY:10 -maxY:40 -perChunk:7 -biome:12|140|30|158|11|26
     >
}

**Comment by CheekyBrit** [comment]
The coal config works but any with specific biomes to spawn in don't spawn at all

**Comment by Terrails** [comment]
its working now, I rewritten the whole generation system and tested it, just gotta wait for curse to approve the files
