### ISSUE TITLE
[Bug] More config entries = less spawns

### ISSUE THREAD

**Issue by Tetrajak** [Terrails/OreController#5]
Minecraft Version: 1.12.2
Forge Version: build 2554
Mod Version: 1.0.5

While testing, I've observed that the more lines that are put into the config file, the less each one ends up spawning. These configs aren't even for the same biomes, yet the more of them there are the less ore is in the ground.

**Comment by Terrails** [comment]
I'm not sure what could be causing this issue since I'm just looping through a loop, can you give me your config so I can test it out?
