### ISSUE TITLE
Multiple Ore Controls

### ISSUE THREAD

**Issue by MokahTGS** [Terrails/OreController#6]
`# Configuration file

"general settings" {
    B:Generate=true

    S:"Ore Generation" <
            abyssalcraft:shoggothbiomass -minVein:1 -maxVein:2 -minY:5 -maxY:100 -perChunk:5 -dimension:10 -replace:minecraft:dirt
            abyssalcraft:stone|7 -minVein:5 -maxVein:10 -minY:5 -maxY:100 -perChunk:5 -dimension:10 -replace:minecraft:stone
         >
}`

I've tried this with the 0.11 version and while I'm getting both types of blocks spawning, the biomass one is replacing air blocks instead of dirt.

**Comment by Terrails** [comment]
Should be fixed... by accident added +8 offset y.
