### ISSUE TITLE
Generating things within generated things?

### ISSUE THREAD

**Issue by Darkmega18** [Terrails/OreController#9]
Is there a way that you can make the generator able to generate blocks within other types of blocks that it has generated, like maybe "generation phases"?
For example a pass of stone generated in the air in a void world, then, afterwards, a pass of ores or other blocks to generate within or over the stone that the mod had just then generated to propagate resources within them?

**Comment by Terrails** [comment]
Not really possible. Its a good idea though. I didn't work on this mod for a long time since of the various changes in 1.13. If I get some motivation to update the mod, I might consider this feature.

**Comment by Darkmega18** [comment]
well darn. atleast I tried. Thanks anyway.
